list: $/shohabbos/multiwallet/models/balance/columns.yaml
modelClass: Shohabbos\Multiwallet\Models\Balance
title: Balance
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'shohabbos/multiwallet/balance/update/:id'
